MySite/MySite/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("mysite_app.urls")),
    path('', include("mysite_blog.urls")),
    path('', include("mysiteDashboard.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MySite/mysiteDashboard/urls.py
from django.urls import path
from . import views


app_name = "url_dashboard"

urlpatterns = [
    
    path("dashboard/", views.info , name= "info_dashboard"),
    path("dashboard/mine/detail/<detail_id>", views.detail_main , name= "main_edit"),
    path("dashboard/mine/contact/<contact_id>/", views.contact_details , name= "contact_details"),
    path("dashboard/update/<main_id>/" , views.update_main , name= "Update_info"),
    path("dashboard/about/" , views.update_about , name= "update_about"),
    path("dashboard/service/<service_id>" , views.update_service , name= "update_service"),
    path("dashboard/add/post" , views.add_post , name= "add_post"),
    path('dashboard/post/details/<details_id>/' , views.display_blog , name="details_post"),
    path('dashboard/post/update/<post_id>/' , views.post_update , name="update_post"),
    path("dashboard/post/delete/<details_id>/" , views.delete_post , name= "delate_post"),
    path("dashboard/contact/delete/<contact_id>/" , views.contact_delete , name= "delate_contact"),
   
    
    
  
]

MySite/mysite_app/urls.py
from django.urls import path
from . import views


app_name = "url_main"

urlpatterns = [
    
    path("" , views.index , name= "index_page"),
    path("About/" , views.about , name= "about_page"),
    # path("Services/" , views.services , name= "services_page"),
    path("Contact/" , views.contact , name= "contact_page"),
]

MySite/mysite_blog/urls.py
from django.urls import path
from . import views


app_name = "url_blog"

urlpatterns = [
    
    path('blogs/' , views.display , name="blog_page"),
    # path('blogs/Add' , views.add_post , name="add_post"),
    path("blogs/details/<post_id>", views.detail_post, name="details_post"),
  
]

MySite/mysite_app/models.py
from django.db import models 

# Create your models here.


class MainModel(models.Model):
    
    title = models.CharField(max_length=1024)
    description = models.TextField()
    image = models.ImageField(upload_to="images/", default="images/default.jpg")
    
    
    
class About(models.Model):
    
    title = models.CharField(max_length=1024)
    about_content = models.TextField()
    image = models.ImageField(upload_to="images/", default="images/default.jpg")
    

class Services(models.Model):
    
    title = models.CharField(max_length=1024)
    service_content = models.TextField()
    
    
class Contact(models.Model):
    
    name = models.CharField(max_length=102)
    email = models.EmailField()
    Phone = models.CharField(max_length=50)
 
    

MySite/mysite_app/views.py
from django.shortcuts import render , redirect
from django.http import HttpRequest , HttpResponse 
from .models import MainModel , About , Services , Contact

# Create your views here.

def index(request : HttpRequest):
    
    result = MainModel.objects.all()
    services = Services.objects.all()
    
    
    f_content = result[0] 
    s_content = result[1]
    t_content = result[2]


    f_service = services[0]
    s_service = services[1]
    t_service = services[2]
            
    context = {
        "content1" : f_content,
        "content2" : s_content,
        "content3" : t_content,
        "services1" : f_service,
        "services2" : s_service,
        "services3" : t_service,
        
        }
         
    return render(request , "main/index.html" , context )



def about(request : HttpRequest):

    result = About.objects.all().order_by("-id")
    
    last_content = result[0]        
    context = {
        "results" : last_content,
        }

    return render(request , "main/about.html" , context )


def contact(request : HttpRequest):

    if request.method == "POST":
            new_contact = Contact(name = request.POST["name"], email = request.POST["email"],  Phone = request.POST["phone"])
            new_contact.save()
            
            return redirect("url_main:index_page")
    return render(request, "main/contact.html")
    

   
        

MySite/mysite_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'main/css/styleSrvice.css' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">


    <title> Home</title>
</head>
<body>
 
  <div class="container-fluid">

    
  
    <nav class="navbar navbar-expand-lg  navbar bg-light" data-bs-theme="light" >
        <div class="container-fluid">

          <a class="navbar-brand" href="{% url 'url_main:index_page' %}"><img style="width: 100px;" src="{% static 'img/main/images.png' %}" alt=""></a>
          <button  class="navbar-toggler"  type="button"  data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'url_main:index_page' %}">Home</a>
            </li>

            

              <li class="nav-item">
                <a class="nav-link" href="{% url 'url_main:about_page' %}">About</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'url_main:contact_page' %}">Contact</a>
              </li>
              
              

              <li class="nav-item">
                <a class="nav-link " href="{% url 'url_blog:blog_page' %}">Blog</a>
              </li>
              <li class="nav-item ">
                <a class="nav-link " style="margin-left: 1000px;" href="{% url 'url_dashboard:info_dashboard' %}">Dash</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      
</div>

{% block content %}


{% endblock %}

<footer class="bg-light text-lg-start">
   

    <hr class="m-0" />

    <div class="text-center py-4 align-items-center">
      <p><b>Follow me on social media</b> </p>
      
      <a href="https://twitter.com/MDBootstrap" class="btn btn-primary m-1" role="button" rel="nofollow"
        target="_blank">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="https://github.com/MJHHaL" class="btn btn-primary m-1" role="button" rel="nofollow"
        target="_blank">
        <i class="fab fa-github"></i>
      </a>
    </div>

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2023 Copyright:
      <a class="text-dark" href="https://mdbootstrap.com/">MJHHaL</a>
    </div>
    <!-- Copyright -->
  </footer>
  
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</html>