MySite/MySite/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("mysite_app.urls")),
    path('', include("mysite_blog.urls")),
    path('', include("mysiteDashboard.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MySite/mysiteDashboard/urls.py
from django.urls import path
from . import views


app_name = "url_dashboard"

urlpatterns = [
    
    path("dashboard/", views.info , name= "info_dashboard"),
    path("dashboard/mine/detail/<detail_id>", views.detail_main , name= "main_edit"),
    path("dashboard/mine/contact/<contact_id>/", views.contact_details , name= "contact_details"),
    path("dashboard/update/<main_id>/" , views.update_main , name= "Update_info"),
    path("dashboard/about/" , views.update_about , name= "update_about"),
    path("dashboard/service/<service_id>" , views.update_service , name= "update_service"),
    path("dashboard/add/post" , views.add_post , name= "add_post"),
    path('dashboard/post/details/<details_id>/' , views.display_blog , name="details_post"),
    path('dashboard/post/update/<post_id>/' , views.post_update , name="update_post"),
    path("dashboard/post/delete/<details_id>/" , views.delete_post , name= "delate_post"),
    path("dashboard/contact/delete/<contact_id>/" , views.contact_delete , name= "delate_contact"),
   
    
    
  
]

MySite/mysiteDashboard/models.py
from django.db import models

# Create your models here.


class owner(models.Model):

    title = models.CharField(max_length=102)
    content = models.TextField()
    image = models.ImageField(upload_to="images/", default="images/default.jpg")

MySite/mysiteDashboard/views.py
from django.shortcuts import render , redirect
from django.http import HttpRequest , HttpResponse 
from .models import owner
from mysite_app.models import MainModel , About , Services , Contact
from mysite_blog.models import Posts 

# Create your views here.


def info(request : HttpRequest):
    
    result = MainModel.objects.all()
    posts = Posts.objects.all()
    about = About.objects.all().order_by("-id")
    con = Contact.objects.all()
    service = Services.objects.all()
    about_index = about[0]
    
    f_content = result[0]
    s_content = result[1]
    t_content = result[2]
    context =  { 
    "result1" : f_content ,
    "result2" : s_content ,
    "result3" : t_content ,
    "postsID" : posts,
    "about_result" :about_index,
    "contacts" : con,
    "services" : service
    
    }
            
    return render(request , "dashboards/dashboard.html" , context )



def detail_main(request : HttpRequest , detail_id):
    
        details = MainModel.objects.get(id = detail_id)
        return render(request, "AppSection/details_main.html", {"detail" : details})


def update_main(request : HttpRequest , main_id):
    
    data = MainModel.objects.get(id=main_id)
    if request.method == "POST":
        
        data.title = request.POST["title"]
        data.description = request.POST["description"]
        data.image = request.FILES["image"]
        data.save()
        return redirect("url_dashboard:info_dashboard")

    return render(request, "AppSection/update.html" , {"result" : data})
 
 
#  ------------------------------------------------------------------------------ 
    
def update_about(request : HttpRequest):
    
        if request.method == "POST":
            new_info = About(title= request.POST["title"], about_content = request.POST["content"],  image = request.FILES["image"])
            new_info.save()
            
            return redirect("url_dashboard:info_dashboard")
        return render(request, "AppSection/about_edit.html")
    
# -------------------------------------------------------------------------------
def update_service(request : HttpRequest , service_id):
    
    data = Services.objects.get(id=service_id)
    
    if request.method == "POST":
        data.title = request.POST["title"]
        data.service_content = request.POST["service_content"]
        data.save()
            
        return redirect("url_dashboard:info_dashboard")
    return render(request, "AppSection/service_edit.html")
    
# ------------------------------------------------------------------------------- 
def add_post(request : HttpRequest):
    
        if request.method == "POST":
            
            Posts(
                title= request.POST["title"],
                content = request.POST["content"] ,
                publish_date = request.POST["publish_date"], 
                image = request.FILES["image"]).save()
            
            return redirect("url_dashboard:info_dashboard")
        return render(request, "BlogSection/add_post.html" )
    
    
    
    
def post_update(request : HttpRequest , post_id ):

    post = Posts.objects.get(id = post_id)

    if request.method == "POST":
            post.title = request.POST["title"]
            post.content = request.POST["content"]
            post.publish_date = request.POST["publish_date"]
            post.image = request.FILES["image"]

            post.save()
            return redirect("url_dashboard:info_dashboard")
    return render(request , "BlogSection/update_post.html" ,  {"posts" : post})



def delete_post(request : HttpRequest, details_id):
    post = Posts.objects.get(id=details_id)
    post.delete()
    return redirect("url_dashboard:info_dashboard")



# ---------------------------------------------
def display_blog(request : HttpRequest , details_id):
         
    details = Posts.objects.get(id = details_id)  
    context = {
             "posts" : details
              } 
         
    return render(request , "blogSection/details_post.html" , context )

# -------------------------------------------------------------------
def contact_details(request : HttpRequest , contact_id):
         
    contact_details = Contact.objects.get(id = contact_id) 
     
    context = {
             "contact" : contact_details
              } 
         
    return render(request , "AppSection/contact_details.html" , context )


def contact_delete(request : HttpRequest, contact_id):
    
    contact = Contact.objects.get(id=contact_id)
    contact.delete()
    return redirect("url_dashboard:info_dashboard")

MySite/mysiteDashboard/templates/dashboards/dashboard.html
{% extends 'master.html' %}
{% load static %}
{% block title %} {% endblock %}

{% block content %}

<style>
    .my-custom-scrollbar {
position: relative;
height: 400px;
overflow: auto;
}
.table-wrapper-scroll-y {
display: block;
width: auto;
}

.marg{
    margin: 2px;
}
</style>
 
<div class="container text-center " style="margin-right: 100px; overflow: hidden;">
    <div class="table-responsive "  >
        <div class="table-wrapper ">
            <div class="table-title">
                <div style="color: brown;" class="col-sm-4"><h2><b>Home Details</b></h2></div>
                <div class="row">
                    
                </div>
            </div>
            <table class=" table-bordered  table-responsive">
                <thead>
                    <tr>
                        <th>image</th>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                    
                </thead>
                <tbody>
                    
            <tr>
                <th scope="row "> {{ result1.title }} </th>
                <td><img class="m-2" style="width:150px " src="{{result1.image.url}}"></td>
                <td>{{result1.description}}</td>
                <td><a  href="{% url 'url_dashboard:main_edit' result1.id %}" class="btn btn-info m-2">Details</a></td>
                
            </tr>
            <tr>
                <th scope="row "> {{ result2.title }} </th>
                <td><img class="m-2" style="width:150px" src="{{result2.image.url}}"></td>
                <td>{{result2.description}}</td>
                <td><a  href="{% url 'url_dashboard:main_edit' result2.id %}" class="btn btn-info m-2">Details</a></td>
            </tr>
            <tr>
                <th scope="row "> {{ result3.title }} </th>
                <td><img class="m-2" style="width:150px;" src="{{result3.image.url}}"></td>
                <td>{{result3.description}}</td>
                <td><a  href="{% url 'url_dashboard:main_edit' result3.id %}" class="btn btn-info m-2">Details</a></td>
            </tr>     
            </tbody>
            </table>
        </div>
    </div>
    <div class="table-responsive table-wrapper ">
    
        <div class="container  text-center  " style="margin-right: 100px;">
            
            <table class="table-responsive-auto table-wrapper table-bordered  " >
               
                <thead>
                    <tr>
                     <th><b><h4>Services</h4></b></th>
                     <th><b><h4>Content</h4></b></th>
                    </tr>
                </thead>
                <tbody>
                    {% for service in services  %}
                    <tr>
                        <td><div class="m-2">{{ service.title }}</div></td>
                        <td>{{ service.service_content }}</td>
                        <td>
                            <a href="{% url 'url_dashboard:update_service' service.id %}" class="btn btn-danger m-2">Edit</a>
        
                        </td>
                 </tr>
                 {% endfor %}
                 
             </tbody>
            </table>
         </div> 
    </div>
    <hr>
    <div class="table-wrapper ">
        
        <div class="row ">
            
            <div class="col-6">
  
          <table class="table-bordered ">
              <thead>
                  <tr>
                      <th scope="">Name</th>
                      <th scope="">Email</th>
                      <th scope="" >Phone</th>
                      <th scope="" >-</th>
                      
                      
                    </tr>
                </thead>
                <tbody>
                    
                    {% for contact in contacts  %}
                    <tr>
                        
                        <td><div class="m-2">{{contact.name}}</div></td>
                        <td><div class="m-2">{{contact.email}}</div></td>
                        <td><div class="m-2">{{contact.Phone}}</div></td>
                        <td><a href="{% url 'url_dashboard:delate_contact' contact.id %}"><i style="color: rgb(217, 7, 7);" class="fas fa-trash m-2"></i></a></td>
                        </tr>
                        
                        {% endfor %}
                        
                        
                    </tbody>
                    
                </table>
                
            </div>
            <div class="col-6">
                <table class="table-bordered table-responsive">
                    <thead>
                        
                        <th scope="col">Title</th>
                        <th scope="col">Content</th>
                        <th scope="col" >Image</th>
                    </thead>
                    <tbody>
                        
                    <tr>
                        
                        <td><div class="m-2">{{about_result.title}}</div></td>
                        <td><div class="m-2">{{about_result.about_content}}</div></td>
                        <td><img class="m-2" style="width:150px" src="{{about_result.image.url}}"></td>
                          <td><a href="{% url 'url_dashboard:update_about' %}"><i style="color: rgb(253, 211, 0);" class="fas fa-pen m-2"></i></a></td>
                        </tr>
                        
                        
                        
                    </tbody>
                </table>
            </div>
            
        </div>
    </div>
</div>


  
<hr>
    
    <div class="container text-center pb-5" style="margin-right: 100px; ">
        
        <div class="table-responsive table-wrapper-scroll-y my-custom-scrollbar">
            <div class="table-wrapper table-bordered table-striped mb-0">
                <h2>Blog</h2>
                <div style="margin-left: 90%;">   
                    <a href="{% url 'url_dashboard:add_post'%}"><p><i class="fas fa-plus "  style="color: rgb(44, 197, 44); size: 30px; "></i></p></a>
                </div>
                <div class="table-title">
                    <div class="row">
                        
                    </div>
                    <table class="table table-responsive ">
                        <thead>
                            <tr>
                                <th scope="col"> </th>
                                <th scope="col">Image</th>
                                <th scope="col">Title</th>
                                <th scope="col" >Content</th>
                                <th scope="col">Date</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                            {% for post in postsID  %}
                            <tr>
                                <th scope="row "></th>
                                <td><img style="width:50px" src="{{post.image.url}}"></td>
                    <td><a href="{% url 'url_dashboard:details_post' post.id %}"><h6> {{ post.title }} </h6></a></td>
                    
                    <td >
                        <div style="font-size: 10px;"> 
                            
                            {{post.content}}
                        </div>
                    </td>
                    <td>{{post.publish_date}}</td>
                </tr>
            
                {% endfor %}
                
                
            </tbody>
        </table>  
        
        </div> 
        
    </div>
    
    </div>
    
     
   

</div>






{% endblock %} 

MySite/mysiteDashboard/templates/dashboards/test.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
        
            <div class="mt-3">
              <label class="form-label">Title</label>
              <input type="text" name="title" class="form-control" />
            </div>
        
            <div class="mt-3">
              <label class="form-label">Content</label>
              <textarea class="form-control" name="content"></textarea>
            </div>
        

              <div class="mt-3">
                <label>Choose File:</label>
                <input type="file" name="image" class="form-control"/>
              </div>
        
              <br/>
              <input type="submit" class="btn btn-primary" value="New info" />
        
            
        
        </form>
</body>
</html> -->


<div class="row">

  <div class="rew">
      <div class="col-3">test</div>
      <div class="col">test</div>
      <div class="col">test</div>

  </div>

</div>