Biography/Biography/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
]

Biography/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path("",                    views.index,            name="index"),
    path("auth/",               views.auth,             name="auth"),
    path("edit/",               views.addNews,          name="edit"),
    path("bio/",                views.bio,              name="bio"),
    path("pro/",                views.pro,              name="pro"),
    path("contact/",           views.contact,         name="contact"),
    path("intell/",             views.intell,           name="intell"),
    path("details/<new_id>/",   views.newDetails,       name="newDetails"),
    path("review/<new_id>/",    views.comment,          name="comment"),
    path("delete/<new_id>/",    views.newsDelete,       name="newsDelete"),
   
    path("addUser/",            views.addUser,          name="addUser"),
]

Biography/main/models.py
from django.db import models

# Create your models here.
class News(models.Model):

    title       = models.CharField(max_length=200)
    content     = models.TextField()
    writingDate = models.DateTimeField(auto_now_add=True)

class Comment(models.Model):

    new        = models.ForeignKey(News, on_delete=models.CASCADE)
    name        = models.CharField(max_length=512)
    content     = models.TextField()
    writingDate  = models.DateTimeField(auto_now_add=True)

class Usr(models.Model):

    usrname         = models.CharField(max_length=12)
    password        = models.CharField(max_length=12)


class Msgs(models.Model):

    name        = models.CharField(max_length=512)
    email       = models.CharField(max_length=512)
    message     = models.TextField()
    writingDate  = models.DateTimeField(auto_now_add=True)

Biography/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from .models import News, Comment , Usr, Msgs
# Create your views here.



################################################################
def index(request : HttpRequest):
    news = News.objects.all()
    context = {"news" : news}
    return render(request, "main/index.html", context)
################################################################
def addNews(request : HttpRequest):
    if request.method == "POST":
        newNews = News(title= request.POST["title"], content = request.POST["content"])
        newNews.save()
        return redirect("main:index")
    news = News.objects.all()
    context = {"news" : news}
    return render(request, "main/edit.html", context)
################################################################
def newDetails(request : HttpRequest, new_id):
    new = News.objects.get(id= new_id)
    comments = Comment.objects.filter(new=new)
    return render(request, "main/newDetails.html", {"new" : new, "comments" : comments})
################################################################
def comment(request : HttpRequest, new_id):
    if request.method == "POST":
        new = News.objects.get(id=new_id)
        newComment = Comment(new = new, name= request.POST["name"], content = request.POST["content"])
        newComment.save()
    return redirect("main:newDetails", new_id=new_id)
################################################################
def newsDelete(request : HttpRequest, new_id):
    new = News.objects.get(id=new_id)
    new.delete()
    return redirect("main:edit")
################################################################
def bio(request : HttpRequest):
    return render(request, "main/bio.html")
################################################################
def pro(request : HttpRequest):
    return render(request, "main/pro.html")
################################################################
def contact(request : HttpRequest):
     return render(request, "main/contact.html")
################################################################
def intell(request : HttpRequest):
    return render(request, "main/intell.html")
################################################################
def addUser(request : HttpRequest):
    if request.method == "POST":
        newusr = Usr(usrname= request.POST["usrname"], password = request.POST["password"])
        newusr.save()
        return redirect("main:index")
    news = Usr.objects.all()
    context = {"news" : news}
    return render(request, "main/edit.html", context)
################################################################
def auth(request : HttpRequest):
    if request.method == "POST":
        authUser = Usr(usrname= request.POST["usrname"], password = request.POST["password"])
        usersDict = Usr.objects.all()
        if(authUser in usersDict):
            flag:int=1
            return (redirect("main:edit"),flag)
        else:
            return redirect("main:index")
    return render(request, "main/index.html")
################################################################

Biography/main/templates/main/auth.html
{% extends 'main/base.html' %}


{% block content %}

<div class="w3-container w3-cyan">
    <h2>Check User</h2>
    
    <div class="w3-row-padding" action="{% url 'main:auth' %}" method="POST">
        {% csrf_token %}
        
        <div class="w3-row-padding">
            <div class="w3-half">
              <input class="w3-input w3-border" type="text" placeholder="Username" name="usrname">
            </div>

            <div class="w3-half">
              <input class="w3-input w3-border" type="text" placeholder="Password" name="password">
            </div>

            <br/>
            <div class="w3-quarter; p-4">
            <input type="submit" class="w3-btn w3-white" value="login" />
            </div>
        </div>
    </div>
    
    </div>


{% endblock %}

Biography/main/templates/main/bio.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<img src="{% static '/images/bio.png' %}" alt="Girl in a jacket" style="width:400px;height:150px;">


<div id="infostrip" style="background:teal;">
  <h1>Greetings
    <hr>
  </h1>
  <svg class="icon icon-camera">
    <use xlink:href="#icon-camera">
      <symbol id="icon-camera" viewBox="0 0 32 32">
        <title>camera</title>
        <path d="M9.5 19c0 3.59 2.91 6.5 6.5 6.5s6.5-2.91 6.5-6.5-2.91-6.5-6.5-6.5-6.5 2.91-6.5 6.5zM30 8h-7c-0.5-2-1-4-3-4h-8c-2 0-2.5 2-3 4h-7c-1.1 0-2 0.9-2 2v18c0 1.1 0.9 2 2 2h28c1.1 0 2-0.9 2-2v-18c0-1.1-0.9-2-2-2zM16 27.875c-4.902 0-8.875-3.973-8.875-8.875s3.973-8.875 8.875-8.875c4.902 0 8.875 3.973 8.875 8.875s-3.973 8.875-8.875 8.875zM30 14h-4v-2h4v2z"></path>
      </symbol>
    </use>
  </svg>

  <p>I would like to welcome you vistor to my website!</p>
  <p>Thankfull to the time and the effort that brought you over, and hoping to find out a common ground.</p>
</div>

<div id="infostrip" style="background:#7d5056f7;">
  <h1>Personal Information
    <hr>
  </h1>
  <svg class="icon icon-fire">
    <use xlink:href="#icon-fire">
      <symbol id="icon-fire" viewBox="0 0 32 32">
        <title>fire</title>
        <path d="M10.031 32c-2.133-4.438-0.997-6.981 0.642-9.376 1.795-2.624 2.258-5.221 2.258-5.221s1.411 1.834 0.847 4.703c2.493-2.775 2.963-7.196 2.587-8.889 5.635 3.938 8.043 12.464 4.798 18.783 17.262-9.767 4.294-24.38 2.036-26.027 0.753 1.646 0.895 4.433-0.625 5.785-2.573-9.759-8.937-11.759-8.937-11.759 0.753 5.033-2.728 10.536-6.084 14.648-0.118-2.007-0.243-3.392-1.298-5.312-0.237 3.646-3.023 6.617-3.777 10.27-1.022 4.946 0.765 8.568 7.555 12.394z"></path>
      </symbol>
    </use>
  </svg>

  <p> My Name is Harun Alrasheed</p>
  <p> And I enjoy sharing expiriance with others and get their expiriance or feed back in return</p>
</div>

<div id="infostrip" style="background:#4c4c4c;">
  <h1>Sharing Memories
    <hr>
  </h1>
  <svg class="icon icon-bug">
    <use xlink:href="#icon-bug"></use>
    <symbol id="icon-bug" viewBox="0 0 32 32">
      <title>bug</title>
      <path d="M32 18v-2h-6.040c-0.183-2.271-0.993-4.345-2.24-6.008h5.061l2.189-8.758-1.94-0.485-1.811 7.242h-5.459c-0.028-0.022-0.056-0.043-0.084-0.064 0.21-0.609 0.324-1.263 0.324-1.944 0-3.305-2.686-5.984-6-5.984s-6 2.679-6 5.984c0 0.68 0.114 1.334 0.324 1.944-0.028 0.021-0.056 0.043-0.084 0.064h-5.459l-1.811-7.242-1.94 0.485 2.189 8.758h5.061c-1.246 1.663-2.056 3.736-2.24 6.008h-6.040v2h6.043c0.119 1.427 0.485 2.775 1.051 3.992h-3.875l-2.189 8.757 1.94 0.485 1.811-7.243h3.511c1.834 2.439 4.606 3.992 7.708 3.992s5.874-1.554 7.708-3.992h3.511l1.811 7.243 1.94-0.485-2.189-8.757h-3.875c0.567-1.217 0.932-2.565 1.051-3.992h6.043z"></path>
    </symbol>
  </svg>

  <p> Prode to share some of my memories with you</p>
  <p> </p>
</div> 

    <div id="section6">
        <div class="grid col-5">
          <div class="col test"><img src="{% static '/images/me01.jpg' %}" alt="testimonial image" />
            <div class="testText">
              <div class="inner"><h4>My first day in education was so intense. When I think back how come as a child I survived and decided to continue my schooling the second day in that school was just a miracle.</h4> </div>
            </div>
            <div class="testName">
              <div class="testIcon"><svg class="icons">
                  <use xlink:href="#quote"></use>&nbsp;
                </svg> <svg class="icons plus">
                  <use xlink:href="#quoteplus"></use>&nbsp;
                </svg></div>
              <h4>Memories <strong>Go long long back</strong></h4>
            </div>
          </div>
          <div class="col test"><img src="{% static '/images/me02.jpg' %}"alt="testimonial image" />
            <div class="testText">
              <div class="inner"><h4>Sports was the best way to conceal a lot of things for me such as that I was bad in socialization except when the topic have to do with a sport relates to it. It is worth mentioning that I am Alnasser club enthusiast and we go back since the beginning of memories.</h4></div>
            </div>
            <div class="testName">
              <div class="testIcon"><svg class="icons">
                  <use xlink:href="#quote"></use>&nbsp;
                </svg> <svg class="icons plus">
                  <use xlink:href="#quoteplus"></use>&nbsp;
                </svg></div>
              <h4>Sports <strong>and enthusiasim</strong></h4>
            </div>
          </div>
          <div class="col test"><img src="{% static '/images/me03.jpg' %}"alt="testimonial image" />
            <div class="testText">
              <div class="inner"><h4>ID card came in a companionship with the determination to start working out of the family businesses, it was a permission to walk my own way.</h4></div>
            </div>
            <div class="testName">
              <div class="testIcon"><svg class="icons">
                  <use xlink:href="#quote"></use>&nbsp;
                </svg> <svg class="icons plus">
                  <use xlink:href="#quoteplus"></use>&nbsp;
                </svg></div>
              <h4>ID <strong>and Personality</strong></h4>
            </div>
          </div>
          <div class="col test"><img src="{% static '/images/me05.jpg' %}"alt="testimonial image" />
            <div class="testText">
                <div class="inner"><h4>Saudi Arabia in transitioning for an economic reform, and I believe that Entrepreneuring is the key to that reform. That is the commitment that I vow to contribute to the country development process.</h4></div>
              </div>
              <div class="testName">
                <div class="testIcon"><svg class="icons">
                    <use xlink:href="#quote"></use>&nbsp;
                  </svg> <svg class="icons plus">
                    <use xlink:href="#quoteplus"></use>&nbsp;
                  </svg></div>
                <h4>Responsability <strong>Entrepreneuring</strong></h4>
              </div>
            </div>
          </div>
        </div>
      </div>


{% endblock %}

Biography/main/templates/main/contact.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<img src="{% static '/images/contact.png' %}" alt="Girl in a jacket" style="width:650px;height:150px;">

<main>
    <!-- Contact -->
    <section class="bg--secondary-color pt3 pb3">
        <div class="container">
            <div class="mb2 align--center">
                <h3 class="mb1">Write to reach me</h3>
            </div>
            <form>
                {% csrf_token %}
                <div class="grid-row">
                    <div class="grid-column span-half mt1">
                        <label class="label" for="name">Name</label>
                        <input class="form-control" id="name" type="text">
                    </div>
                    <div class="grid-column span-half mt1">
                        <label class="label" for="email">Email</label>
                        <input class="form-control" id="email" type="email">
                    </div>
                </div>
                <label class="label mt1" for="message">Message</label>
                <textarea class="form-control" id="message"></textarea>
                <div class="align--right mt1">
                    <button class="btn btn--outline">Send</button>
                </div>
            </form>
        </div>
    </section>
    
</main>

{% endblock %}

Biography/main/templates/main/edit.html
{% extends 'main/base.html' %}

{% block title %} News {% endblock %}

{% block content %}


<div class="w3-container w3-white">
<h2>Write a new News</h2>

<form action="" method="POST">
    {% csrf_token %}

    <label class="form-label">Title</label>
    <input type="text" name="title" class="form-control" />

    <label class="form-label">content</label>
    <textarea class="form-control" name="content"></textarea>

      <br/>
      <input type="submit" class="w3-btn w3-blue" value="Post" />

</form>

</div>
<hr/>
<div class="w3-container w3-white">
    <h2> Delete a News!</h2>

    <div class="row">
        {% for new in news %}
            
            <div class="col-3">
                <div class="p-4 shadow" >
                    <a href="{% url 'main:newDetails' new.id %}"><h4>{{ new.title }}</h4></a>
                    <p>{{ new.content }}</p>
                    <h6>Date: {{ new.writingDate }}</h6>
                    <div class="m-3 d-flex gap-2"><a href="{% url 'main:newsDelete' new.id %}" class="btn btn-danger">Delete</a></div>
                </div>
            </div>
        {% endfor %}


    </div>
</div>
<hr/>
<div class="w3-container w3-white">
    <h2>New User</h2>
    
    <div class="w3-row-padding" action="{% url 'main:addUser' %}" method="POST">
        {% csrf_token %}
        
        <div class="w3-row-padding">
            <div class="w3-half">
              <input class="w3-input w3-border" type="text" placeholder="Username" name="usrname">
            </div>

            <div class="w3-half">
              <input class="w3-input w3-border" type="text" placeholder="Password" name="password">
            </div>

            <br/>
            <div class="w3-quarter; p-4">
            <input type="submit" class="w3-btn w3-blue" value="Creat" />
            </div>
        </div>
    </div>
    
    </div>

   
{% endblock %}

Biography/main/templates/main/index.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <style>
        
        * {
            box-sizing: border-box;
            }

            body, html {
            width: 100%;
            height: 100%;
            background: orange;
            justify-content: center;
            }

            .bodyu {
            width: 100%;
            height: 100%;
            display: flex;
            align-items: center;
            justify-content: center;
            background: #609EA2;
            padding: 60px
            }

            .wrapper {
            display: flex;
            width: 90%;
            justify-content: space-around;
            }

            .card {
            width: 280px;
            height: 360px;
            border-radius: 15px;
            padding: 1.5rem;
            background: orange;
            position: relative;
            display: flex;
            align-items: flex-end;
            transition: 0.4s ease-out;
            box-shadow: 0px 7px 10px rgba(0, 0, 0, 0.5);
            }
            .card:hover {
            transform: translateY(20px);
            }
            .card:hover:before {
            opacity: 1;
            }
            .card:hover .info {
            opacity: 1;
            transform: translateY(0px);
            }
            .card:before {
            content: "";
            position: absolute;
            top: 0;
            left: 0;
            display: block;
            width: 100%;
            height: 100%;
            border-radius: 15px;
            background: rgba(0, 0, 0, 0.6);
            z-index: 2;
            transition: 0.5s;
            opacity: 0;
            }
            .card img {
            width: 100%;
            height: 100%;
            -o-object-fit: cover;
                object-fit: cover;
            position: absolute;
            top: 0;
            left: 0;
            border-radius: 15px;
            }
            .card .info {
            position: relative;
            z-index: 3;
            color: white;
            opacity: 0;
            transform: translateY(30px);
            transition: 0.5s;
            }
            .card .info h1 {
            margin: 0px;
            }
            .card .info p {
            letter-spacing: 1px;
            font-size: 15px;
            margin-top: 8px;
            }
            .card .info button {
            padding: 0.6rem;
            outline: none;
            border: none;
            border-radius: 3px;
            background: white;
            color: black;
            font-weight: bold;
            cursor: pointer;
            transition: 0.4s ease;
            }
            .card .info button:hover {
            background: dodgerblue;
            color: white;
            }

        </style>
        <title> </title>
    
    </head>
    <body>
    <div class="bodyu" style="background-image: url('/static/images/back11.jpg');background-repeat:no-repeat; background-position:inherit; background-attachment: fixed;background-size: cover; margin: 0;padding: 0;overflow:scroll; text-align: center;">
        <div class="wrapper">
          <div class="card"><img src="{% static '/images/bio.jpg' %}"/>
            <div class="info">
              <h1>Biography</h1>
              <p>My brife history</p>
              <button><a href="{% url 'main:bio' %}">Read More</a></button>
            </div>
          </div>
          <div class="card"><img src="{% static '/images/pro.jpg' %}"/>
            <div class="info">
              <h1>Profession</h1>
              <p>What I am good at</p>
              <button><a href="{% url 'main:pro' %}">Read More</a></button>
            </div>
          </div>
          <div class="card"><img src="{% static '/images/intell.jpg' %}"/>
            <div class="info">
              <h1>Intellectual</h1>
              <p>My publications and litreture Reviewal</p>
              <button><a href="{% url 'main:intell' %}">Read More</a></button>
            </div>
          </div>
          <div class="card"><img src="https://images.unsplash.com/photo-1503249023995-51b0f3778ccf?auto=format&amp;fit=crop&amp;w=311&amp;q=80&amp;ixid=dW5zcGxhc2guY29tOzs7Ozs%3D"/>
            <div class="info">
              <h1>Contact Me</h1>
              <p></p>
              <button><a href="{% url 'main:contact' %}">Read More</a></button>
            </div>
          </div>
        </div>
    </div>

    <hr/>
       
    <div>
        <div class="container">
            <h2> Latest News !</h2>

            <div class="row">
                {% for new in news %}
                    
                    <div class="col-3">
                        <div class="p-4 shadow" >
                            <a href="{% url 'main:newDetails' new.id %}"><h4>{{ new.title }}</h4></a>
                            <p>{{ new.content }}</p>
                            <h6>Date: {{ new.writingDate }}</h6>
                        </div>
                    </div>
                {% endfor %}


            </div>
        </div>
    </div>
    </body>
</html>

Biography/main/templates/main/intell.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<img src="{% static '/images/lit.webp' %}" alt="Girl in a jacket" style="width:400px;height:350px;">
<div id="infostrip" style="background:teal;">
  <h1>My Publication
    <hr>
  </h1>
  <svg class="icon icon-camera">
    <use xlink:href="#icon-camera">
      <symbol id="icon-camera" viewBox="0 0 32 32">
        <title>camera</title>
        <path d="M9.5 19c0 3.59 2.91 6.5 6.5 6.5s6.5-2.91 6.5-6.5-2.91-6.5-6.5-6.5-6.5 2.91-6.5 6.5zM30 8h-7c-0.5-2-1-4-3-4h-8c-2 0-2.5 2-3 4h-7c-1.1 0-2 0.9-2 2v18c0 1.1 0.9 2 2 2h28c1.1 0 2-0.9 2-2v-18c0-1.1-0.9-2-2-2zM16 27.875c-4.902 0-8.875-3.973-8.875-8.875s3.973-8.875 8.875-8.875c4.902 0 8.875 3.973 8.875 8.875s-3.973 8.875-8.875 8.875zM30 14h-4v-2h4v2z"></path>
      </symbol>
    </use>
  </svg>
  <button><a href="{% static '/images/pdf.pdf' %}">A Framework for the proper implementation, best practices, outlines, and the expected value of the Enterprise Architecture</a></button>
  <p>For the master dgree research project I did research in the information technology regarding the enterprise architecture:</p>
  
</div>

<div id="infostrip" style="background:#7d5056f7;">
  <h1>Future Work and Literature Review
    <hr>
  </h1>
  <svg class="icon icon-fire">
    <use xlink:href="#icon-fire">
      <symbol id="icon-fire" viewBox="0 0 32 32">
        <title>fire</title>
        <path d="M10.031 32c-2.133-4.438-0.997-6.981 0.642-9.376 1.795-2.624 2.258-5.221 2.258-5.221s1.411 1.834 0.847 4.703c2.493-2.775 2.963-7.196 2.587-8.889 5.635 3.938 8.043 12.464 4.798 18.783 17.262-9.767 4.294-24.38 2.036-26.027 0.753 1.646 0.895 4.433-0.625 5.785-2.573-9.759-8.937-11.759-8.937-11.759 0.753 5.033-2.728 10.536-6.084 14.648-0.118-2.007-0.243-3.392-1.298-5.312-0.237 3.646-3.023 6.617-3.777 10.27-1.022 4.946 0.765 8.568 7.555 12.394z"></path>
      </symbol>
    </use>
  </svg>
  <p>Currunt work: The Data Diode to Operate, Maintain, and Protect Airgap Infrastructure</p>
  <p> In a request for starting a research project I had to review the state of art at the field that I am looking into.</p>
  <p> The work now is going on : The Data Diode to Operate, Maintain, and Protect Airgap Infrastructure</p>
</div>


{% endblock %}

Biography/main/templates/main/newDetails.html
{% extends 'main/base.html' %}

{% block title %} Details for {{ blog.title }}  {% endblock %}


{% block content %}

<div class="container">

    <h1>{{ new.title }}</h1>
    <h6>Date: {{ new.writingDate }}</h6>
    <p>{{ new.content }}</p>


    <hr/>

    <div  class="m-3">
        <h3>Reviews :</h3>
        {% for comment in comments  %}
            <div class="p-2 border mt-2">
                <h5>{{ comment.name }}</h5>
                <h6>Date: {{ comment.writingDate }}</h6>
                <p>{{ comment.content }}</p>

            </div>
        {% endfor %}
    </div>

    <div>
        <h3>Add Comment</h3>
        <div>
            <form action="{% url  'main:comment' new.id %}" method="post">
                {% csrf_token %}

                <input type="text" name="name" class="form-control" placeholder="Your Name.." /> 

                <textarea name="content" class="form-control" placeholder="Your Review here..."></textarea>


                <input class="btn btn-primary" type="submit" value="Add Comment" />

            </form>
        </div>
    </div>
</div>

{% endblock %}