Project2/Project2/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

Project2/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('',views.home_page,name='home_page'),
    path('project/',views.project_page,name='project_page'),
    path('about/',views.about_page,name='about_page'),
    path('contact/',views.contact_page,name='contact_page'),
    path('coffee/detail/',views.coffee_project_detail,name='coffee_project_detail'),
    path('alphabet/detail/',views.alphabet_project_detail,name='alphabet_project_detail'),
    
]

Project2/main/models.py
from django.db import models

class Comment(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    images = models.ImageField(upload_to="images/", default="images/default.svg")
    commentDate = models.DateTimeField(auto_now_add=True)

class Contact(models.Model):
    name = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=10)
    email = models.CharField(max_length=25)
    message = models.CharField(max_length=512)

Project2/main/views.py
from django.shortcuts import render
from django.http import HttpRequest,HttpResponse
from main.models import Contact


def home_page(request:HttpRequest):
    return render(request,'main/home_page.html')

def project_page(request:HttpRequest):  
    return render(request,'main/service_page.html')

def about_page(request:HttpRequest):
    return render(request,'main/about_page.html')

def contact_page(request:HttpRequest):
    if request.method == 'POST':
        info = Contact(name = request.POST['name'],phone_number=request.POST['phone'],email=request.POST['email'],message = request.POST['message'])
        info.save()
        return render(request,'main/contact_page.html')
    
    return render(request,'main/contact_page.html')

def coffee_project_detail(request:HttpRequest):
    return render(request,'main/coffee_project_detail.html')

def alphabet_project_detail(request:HttpRequest):
    return render (request,'main/alphabet_project_detail.html')

Project2/main/templates/main/about_page.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} About Page{% endblock %}

{%block content%}
<div class="container">
<div class="w-100 vh-100 d-flex justify-content-center ">
<h4>
     <section class="container my-5">
          <div class="row">
            <div class="col-md-6">
              <h1 class="mb-5">About Me</h1>
              <p class="ms-2">
               Hi, my name is Yazeed and I'm a Student at CTI. <br>
               I have a passion for web development, and I enjoy doing design on adobe xd.
               and I'm always looking for new challenges and opportunities to grow.
              </p>
            </div>
          </div>
        </section>
</h4>
</div>

{% endblock %}

Project2/main/templates/main/alphabet_project_detail.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} Alphabet Project{% endblock %}

{%block content%}


<div class="container justify-content-center">

<!-- Bootstrap Carousel -->
<div class="container-fluid">
    <h1 class="text-center color-text mt-2 mb-5">
        Alphabet App Detail
    </h1>
    <div class="container-fluid">
        <div class="row">
          <div class="col-md-8 mx-auto">
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
              <ul class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
                <li data-target="#myCarousel" data-slide-to="3"></li>
              </ul>
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img src="{% static 'images\alphabet_main_page.png'%}" alt="Image 1">
                </div>
                <div class="carousel-item">
                  <img src="{% static 'images\alphabet_less_page.png'%}" alt="Image 2">
                </div>
                <div class="carousel-item">
                  <img src="{% static 'images\alphabet_game_page.png'%}" alt="Image 3">
                </div>
                <div class="carousel-item">
                  <img src="{% static 'images\alphabet_ach_page.png'%}" alt="Image 4">
                </div>
              </div>
              
            </div>
          </div>
        </div>
      </div>
      <h4 class="mt-3 color-text p-5 ms-5 me-5">
        The application was created for children to learn English letters in an 
        easy and fun way through the clips and games in the application, and 
        also an achievement will be saved on a dedicated page.
        The color was inspired by the sun and the new day.
    </h4>
         
       
  </div>


</div>

     
{% endblock %}

Project2/main/templates/main/base.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  
  
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap');
        @import url("https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css");

    </style>
    <title>YZ | {% block title %} {% endblock %}</title>
</head>
<body>

   <!-- navbar -->
    <nav class="navbar navbar-expand-lg shadow-5-strong">
        
        <div class="container-fluid row-cols-2 pe-5 mb-3">
                <a class="navbar-brand ms-0 me-0 ps-5" href="#"><strong><h1> YZ </h1></strong></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse ms-5 ">
            <ul class="navbar-nav">
                <li class="nav-item ">
                <a class="nav-link active ms-5 me-5" aria-current="page" href="{% url 'main:home_page' %}">Home</a>
                </li>
                
                <li class="nav-item">
                <a class="nav-link ms-5 me-5" href="{% url 'main:project_page' %}">My Projects</a>
                </li>

                <li class="nav-item">
                <a class="nav-link ms-5 me-5" href="{% url 'main:about_page' %}">About Me</a>
                </li>

                <li class="nav-item">
                <a class="nav-link ms-5" href="{% url 'main:contact_page' %}">Contact Me</a>
                </li>   
            </ul>
            </div>
        </div>
    </nav>



    <div class="contener">
       {% block content %}
       
       {% endblock %}
    </div>



    <!--footer-->
    <div class="">

        <footer class="text-center text-white footer-color mt-5">
        <!-- Grid container -->
        <div class="container pt-4 ">
          <!-- Section: Social media -->
        <section class="mb-4">
            <!-- Facebook -->
            <a
              class="btn btn-link btn-floating btn-lg text-dark m-1"
              href="#!"
              role="button"
              data-mdb-ripple-color="dark"
              ><i class="bi bi-facebook"></i>
            </a>
      
            <!-- Twitter -->
            <a
              class="btn btn-link btn-floating btn-lg text-dark m-1"
              href="#!"
              role="button"
              data-mdb-ripple-color="dark"
              ><i class="bi bi-twitter"></i>
            </a>
      
             <!-- Linkedin -->
            <a
              class="btn btn-link btn-floating btn-lg text-dark m-1"
              href="#!"
              role="button"
              data-mdb-ripple-color="dark"
              ><i class="bi bi-linkedin"></i>
            </a>
      
            <!-- Instagram -->
            <a
              class="btn btn-link btn-floating btn-lg text-dark m-1"
              href="#!"
              role="button"
              data-mdb-ripple-color="dark"
              ><i class="bi bi-instagram"></i>
            </a>
    
            <!-- Github -->
            <a
              class="btn btn-link btn-floating btn-lg text-dark m-1"
              href="#!" 
              role="button"
              data-mdb-ripple-color="dark"
              ><i class="bi bi-github"></i>
            </a>
    
        </section>
          <!-- Section: Social media -->
        </div>
        <!-- Grid container -->
      
        <!-- Copyright -->
        <div class="text-center text-dark p-3 footer-color">
          © 2023 Copyright:
          <a class="text-dark" href="{% url 'main:home_page' %}">yazeed.com</a>
        </div>
        <!-- Copyright -->
      </footer>
        
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-fgCeRjCv+awtlhAV5D9YJd5u5l5ew89STBwOD7nN1NcG85KrkziAAU+GM2U9IC6W" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-PH+o/dOJgDX2q3h1XyJb07yAn56xzv3q2C+8fvZzrG49FnHIFgzfDxgjmM7VYpJ5" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/8fe9e9a2f9.js" crossorigin="anonymous"></script>

</body>
</html>

Project2/main/templates/main/coffee_project_detail.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} Coffee Project{% endblock %}

{%block content%}


<div class="container justify-content-center">

<!-- Bootstrap Carousel -->
<div class="container-fluid">
    <h1 class="text-center color-text mt-2 mb-5">
        Binary App Detail
    </h1>
    <div class="container-fluid">
        <div class="row">
          <div class="col-md-8 mx-auto">
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
              <ul class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
                <li data-target="#myCarousel" data-slide-to="3"></li>
              </ul>
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img src="{% static 'images\main_page.png'%}" alt="Image 1">
                </div>
                <div class="carousel-item">
                  <img src="{% static 'images\coffee_page.png'%}" alt="Image 2">
                </div>
                <div class="carousel-item">
                  <img src="{% static 'images\cup_page.png'%}" alt="Image 3">
                </div>
                <div class="carousel-item">
                  <img src="{% static 'images\cart_page.png'%}" alt="Image 4">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <h4 class="mt-3 color-text p-5 ms-5 me-5">
        This project was built on Adobe xd.
        And the goal of the project is to know the good user experience.
        The stakeholder of the project are the owners of coffee shops and suppliers.
        The color of the application was inspired by coffee.
      </h4>
         
       
  </div>


</div>

     
{% endblock %}

Project2/main/templates/main/contact_page.html
{% extends 'main/base.html' %}
{% block title %} Contact Page{% endblock %}


{%block content%}

<div class="color-text  d-flex flex-column justify-content-center align-items-center">

    

    <form class="p-4 rounded-4 contact-form  w-50" action="" method="POST" enctype="multipart/form-data">
    <h1 class="text-center">Contact Me</h1>
    {% csrf_token %}

    <div class="mb-3">
        <input type="text" class="form-control" name="name" placeholder="Enter Your Name">
    </div>

    <div class="mb-3">
        <input type="text" class="form-control" name="phone" placeholder="Enter Your phone">
    </div>

    <div class="mb-3">
      <input type="email" class="form-control" name="email" placeholder="Enter Your Email">
    </div>

    <div class="mb-3">
        <input type="text" class="form-control" name="message" placeholder="Enter a Message">
    </div>
    
    <button type="submit" class="btn btn-primary">Send</button>
    
    </form>
    <hr>
    <div class="row mt-5">
        
            <h3 class="text-center">Contact Information</h3>
            <h4 class="text-center"><i class="bi bi-envelope"></i> Email: Yazeed@gmail.com</h4>
            <h4 class="text-center"><i class="bi bi-phone">Phone : +966505523545</i></h4>
           
    </div>
</div>


{% endblock %}

Project2/main/templates/main/home_page.html
{% extends 'main/base.html' %}
{% block title %} Home Page{% endblock %}

{%block content%}


<div class="w-100 vh-100 d-flex justify-content-center align-items-center main">
    
    <div class="d1"></div>
    <div class="d2"></div>
    <div class="d3"></div>
    <div class="d4"></div>
    <strong>
    <h3 class="position-absolute welcome-sing" >
            Welcome to My website <br>
            here you will find some of my project <br> and about me :)
        </h3>
    </strong>
    
</div>

     
{% endblock %}

Project2/main/templates/main/service_page.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} Service Page{% endblock %}


{%block content%}

<div class="container text-center ">   
    
    <div class="row color-text">
        <h1 class="mt-5"> UI PROJECT </h1>
        
        <div class="col">
            <h2>Binary</h2>
            <img  src="{% static 'images/white_logo.png' %}" class="d-block w-50 project-contant " alt="...">
            <div class="text-center color-text">
                <h5 class="mt-5 mb-2 ps-3 pe-3">
                  This project was built on Adobe xd
                  stakeholders of the project are the owners of coffee shops and suppliers
                  
                </h5>
                <a href="{% url 'main:coffee_project_detail'%}">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Read More</button>
                </a>
            </div>
        </div>

        <div class="col">
            <h2>Alphabet</h2>
            <img  src="{% static 'images/alphabet_logo.png' %}" class="d-block w-50 project-contant" alt="...">
            <div class="text-center color-text mt-5">
                <h5 class="mt-5 mb-2 ps-3 pe-3">
                  This project was built on Adobe xd 
                  stakeholders of the project are the parents and children between 6 - 12 
                </h5>
                <a href="{% url 'main:alphabet_project_detail' %}">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Read More</button>
                </a>
            </div>
        </div>
      </div>
      
    </div>
    

{% endblock %}